
function coeffs = getCoefficientsFromControlPoints(control_points)
    S = zeros( size(control_points) );
    S(1,:) = control_points(1,:);
    S(end,:) = control_points(end,:);
    
    S(2:end-1,:) = (1/6) * (...
        control_points(1:end-2,:) ...
        + 4 * control_points(2:end-1,:) ...
        + control_points(3:end,:) ...
    );

    S_complex = complex( S(1,:), S(2,:) );
    B_complex = complex( control_points(1,:), control_points(2,:) );
    control_matrix = horzcat( ...
        S_complex(1:end-1), ...
        (1/3) * (2 * B_complex(1:end-1) +     B_complex(2:end)), ...
        (1/3) * (    B_complex(1:end-1) + 2 * B_complex(2:end)), ...
        S_complex(2:end)...
    );

    coeffs = getBezierCoefficients( control_matrix );
end